// 全局的mutations-type类型
export const SAVE_LOADING_STATE = 'SAVE_LOADING_STATE';

// 保存登录信息
export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';

// 保存按钮配置
export const SAVE_BUTTON_CONFIG = 'SAVE_BUTTON_CONFIG';

// 保存权限路由
export const SAVE_PERMIT_PATH_INFO = 'SAVE_PERMIT_PATH_INFO';

// 保存权限资源
export const SAVE_PERMIT_RESOURCE_INFO = 'SAVE_PERMIT_RESOURCE_INFO';

// 保存查询参数
export const SAVE_QUERY_PARAMS_INFO = 'SAVE_QUERY_PARAMS_INFO';

// 保存多页签对象
export const SAVE_MULTIPLE_OBJ = 'SAVE_MULTIPLE_OBJ';

// 保存菜单索引
export const SAVE_NAV_INDEX = 'SAVE_NAV_INDEX';

// 保存多页签队列
export const SAVE_TAB_LABELS = 'SAVE_TAB_LABELS';

// 保存下拉数据
export const SAVE_OPTION_LIST_INFO = 'SAVE_OPTION_LIST_INFO';

// 保存页面编辑状态
export const SAVE_PAGE_EDIT_STATE = 'SAVE_PAGE_EDIT_STATE';

// 保存账号销量信息
export const SAVE_ACCOUNT_SALES_VOLUME_INFO = 'SAVE_ACCOUNT_SALES_VOLUME_INFO';

// 保存销售业绩信息
export const SAVE_SALES_PERFORMANCE_COUNT_INFO = 'SAVE_SALES_PERFORMANCE_COUNT_INFO';

// 保存重要参数
export const SAVE_ACCOUNT_MAIN_PARAMS_INFO = 'SAVE_ACCOUNT_MAIN_PARAMS_INFO';

//开发目标完成统计
export const SAVE_DEVELOPMENT_GROUP_COUNT_INFO = 'SAVE_DEVELOPMENT_GROUP_COUNT_INFO';
export const SAVE_DEVELOPER_COUNT_INFO = 'SAVE_DEVELOPER_COUNT_INFO';
export const SAVE_DEVELOPMENT_TYPE_COUNT_INFO = 'SAVE_DEVELOPMENT_TYPE_COUNT_INFO';
export const SAVE_DEVELOPMENT_PRODUCT_LINE_INFO = 'SAVE_DEVELOPMENT_PRODUCT_LINE_INFO';

//各成本区间商品开发数
export const SAVE_COST_DEVELOPMENT_GROUP_INFO = 'SAVE_COST_DEVELOPMENT_GROUP_INFO';
export const SAVE_COST_DEVELOPER_INFO = 'SAVE_COST_DEVELOPER_INFO';
export const SAVE_COST_DEVELOPMENT_TYPE_INFO = 'SAVE_COST_DEVELOPMENT_TYPE_INFO';
export const SAVE_COST_PRODUCT_LINE_INFO = 'SAVE_COST_PRODUCT_LINE_INFO';

//跟单平均时效统计
export const SAVE_ORDER_GROUP_COUNT_INFO = 'SAVE_ORDER_GROUP_COUNT_INFO';
export const SAVE_ORDER_PRODUCT_LINE_INFO = 'SAVE_ORDER_PRODUCT_LINE_INFO';

//供应商平均到样时效
export const SAVE_SUPPLIER_ARRIVAL_INFO = 'SAVE_SUPPLIER_ARRIVAL_INFO';

//开发平均时效统计
export const SAVE_DEVELOPER_TIME_COUNT_INFO = 'SAVE_DEVELOPER_TIME_COUNT_INFO';
export const SAVE_DEVELOPER_PRODUCT_LINE_COUNT_INFO = 'SAVE_DEVELOPER_PRODUCT_LINE_COUNT_INFO';

//TQE工作报表
export const SAVE_DAY_DETAILS_INFO = 'SAVE_DAY_DETAILS_INFO';
export const SAVE_DAY_SUMMARY_INFO = 'SAVE_DAY_SUMMARY_INFO';
export const SAVE_MONTH_SUMMARY_INFO = 'SAVE_MONTH_SUMMARY_INFO';
export const SAVE_ANNUAL_REPORT_INFO = 'SAVE_ANNUAL_REPORT_INFO';

//样品审核报表
export const SAVE_SAMPLE_DEVELOPMENT_GROUP_INFO = 'SAVE_SAMPLE_DEVELOPMENT_GROUP_INFO';
export const SAVE_SAMPLE_PRODUCT_LINE_INFO = 'SAVE_SAMPLE_PRODUCT_LINE_INFO';
export const SAVE_SAMPLE_TQE_REPORT_INFO = 'SAVE_SAMPLE_TQE_REPORT_INFO';

//文案工作报表
export const SAVE_COPY_GROUP_SUMMARY_INFO = 'SAVE_COPY_GROUP_SUMMARY_INFO';
export const SAVE_COPY_GROUP_DETAILS_INFO = 'SAVE_COPY_GROUP_DETAILS_INFO';

//文案编辑报表
export const SAVE_COPY_GROUP_TEAM_INFO = 'SAVE_COPY_GROUP_TEAM_INFO';
export const SAVE_COPY_GROUP_TEAM_ECHART_INFO = 'SAVE_COPY_GROUP_TEAM_ECHART_INFO';
export const SAVE_COPY_GROUP_MEMBER_INFO = 'SAVE_COPY_GROUP_MEMBER_INFO';
export const SAVE_COPY_GROUP_MEMBER_ECHART_INFO = 'SAVE_COPY_GROUP_MEMBER_ECHART_INFO';
export const SAVE_COPY_GROUP_PRODUCTLNE_INFO = 'SAVE_COPY_GROUP_PRODUCTLNE_INFO';
export const SAVE_COPY_GROUP_PRODUCTLNE_ECHART_INFO = 'SAVE_COPY_GROUP_PRODUCTLNE_ECHART_INFO';
export const SAVE_COPY_GROUP_DEVETYPE_INFO = 'SAVE_COPY_GROUP_DEVETYPE_INFO';
export const SAVE_COPY_GROUP_DEVETYPE_ECHART_INFO = 'SAVE_COPY_GROUP_DEVETYPE_ECHART_INFO';


//文案平均耗时统计
export const SAVE_COPY_GROUP_COUNT_INFO = 'SAVE_COPY_GROUP_COUNT_INFO';
export const SAVE_COPY_PRODUCT_LINE_COUNT_INFO = 'SAVE_COPY_PRODUCT_LINE_COUNT_INFO';

//文案目标达成统计
export const SAVE_COPY_GOAL_STATISTICS_INFO = 'SAVE_COPY_GOAL_STATISTICS_INFO';

//设计部任务汇总统计
export const SAVE_DESIGN_TASK_COUNT_INFO = 'SAVE_DESIGN_TASK_COUNT_INFO';

//摄影工作报表
export const SAVE_PHOTO_GROUP_SUMMARY_INFO = 'SAVE_PHOTO_GROUP_SUMMARY_INFO';
export const SAVE_PHOTO_GROUP_DETAILS_INFO = 'SAVE_PHOTO_GROUP_DETAILS_INFO';

//摄影平均耗时统计
export const SAVE_PHOTO_GROUP_TIME_COUNT_INFO = 'SAVE_PHOTO_GROUP_TIME_COUNT_INFO';
export const SAVE_PHOTO_TASK_TYPE_COUNT_INFO = 'SAVE_PHOTO_TASK_TYPE_COUNT_INFO';
export const SAVE_PHOTO_PRODUCT_LINE_COUNT_INFO = 'SAVE_PHOTO_PRODUCT_LINE_COUNT_INFO';

//摄影拍摄明细
export const SAVE_PHOTOGRAPH_DETAILS_INFO = 'SAVE_PHOTOGRAPH_DETAILS_INFO';

//美工工作报表
export const SAVE_ARTIST_GROUP_SUMMARY_INFO = 'SAVE_ARTIST_GROUP_SUMMARY_INFO';
export const SAVE_ARTIST_GROUP_DETAILS_INFO = 'SAVE_ARTIST_GROUP_DETAILS_INFO';

//美工平均耗时统计
export const SAVE_ARTIST_GROUP_TIME_COUNT_INFO = 'SAVE_ARTIST_GROUP_TIME_COUNT_INFO';
export const SAVE_ARTIST_PRODUCT_LINE_COUNT_INFO = 'SAVE_ARTIST_PRODUCT_LINE_COUNT_INFO';

//美工修图明细
export const SAVE_ARTWORK_REPAIR_DETAILS_INFO = 'SAVE_ARTWORK_REPAIR_DETAILS_INFO';

//设计组工作报表
export const SAVE_DESIGN_GROUP_SUMMARY_INFO = 'SAVE_DESIGN_GROUP_SUMMARY_INFO';
export const SAVE_DESIGN_GROUP_DETAILS_INFO = 'SAVE_DESIGN_GROUP_DETAILS_INFO';

//设计组目标完成统计
export const SAVE_DESIGN_GOAL_STATISTICS_INFO = 'SAVE_DESIGN_GOAL_STATISTICS_INFO';

// 亚马逊权限配置
export const SAVE_AM_USER_CONFIG_INFO = 'SAVE_AM_USER_CONFIG_INFO';
export const SAVE_AM_ROLE_CONFIG_INFO = 'SAVE_AM_ROLE_CONFIG_INFO';

//刊登销量统计
export const SAVE_PUBLISH_SALE_COUNT_INFO = 'SAVE_PUBLISH_SALE_COUNT_INFO';


//产品线销售趋势报表
export const SAVE_PRODUCT_LINE_TREND_INFO = 'SAVE_PRODUCT_LINE_TREND_INFO';

//产品权限配置
export const SAVE_PRODUCT_USER_CONFIG_INFO = 'SAVE_PRODUCT_USER_CONFIG_INFO';
export const SAVE_PRODUCT_ROLE_CONFIG_INFO = 'SAVE_PRODUCT_ROLE_CONFIG_INFO';

//仓库统计报表
export const SAVE_STATISTICAL_REPORT_INFO = 'SAVE_STATISTICAL_REPORT_INFO';

//目标完成情况
export const SAVE_TARGET_PERFORMANCE_INFO = 'SAVE_TARGET_PERFORMANCE_INFO';
export const SAVE_TARGET_ENTRY_INFO = 'SAVE_TARGET_ENTRY_INFO';

//订单执行时效
export const SAVE_ORDER_EXECUTION_DAY_INFO = 'SAVE_ORDER_EXECUTION_DAY_INFO';
export const SAVE_ORDER_EXECUTION_WEEK_INFO = 'SAVE_ORDER_EXECUTION_WEEK_INFO';
export const SAVE_ORDER_EXECUTION_MONTH_INFO = 'SAVE_ORDER_EXECUTION_MONTH_INFO';

//销售统计数据报表
export const SAVE_SALES_DATA_REPORT_INFO = 'SAVE_SALES_DATA_REPORT_INFO';

//开发平均数量统计
export const SAVE_DEVELOPER_NUMBER_COUNT_INFO = 'SAVE_DEVELOPER_NUMBER_COUNT_INFO';
export const SAVE_DEVELOPER_LINE_NUMBER_COUNT_INFO = 'SAVE_DEVELOPER_LINE_NUMBER_COUNT_INFO';

//listing动销柱状报表
export const SAVE_LISTING_MOVE_BAR_INFO = 'SAVE_LISTING_MOVE_BAR_INFO';
//listing动销数据报表
export const SAVE_LISTING_MOVE_DATA_INFO = 'SAVE_LISTING_MOVE_DATA_INFO';

//B2B订单时效
export const SAVE_B2B_ORDER_DAY_INFO = 'SAVE_B2B_ORDER_DAY_INFO';
export const SAVE_B2B_ORDER_WEEK_INFO = 'SAVE_B2B_ORDER_WEEK_INFO';
export const SAVE_B2B_ORDER_MONTH_INFO = 'SAVE_B2B_ORDER_MONTH_INFO';

//欠货统计报表
export const SAVE_ARREARS_COUNT_REPORT_INFO = 'SAVE_ARREARS_COUNT_REPORT_INFO';

//账号健康度统计
export const SAVE_ACCOUNT_HEALTH_COUNT_INFO = 'SAVE_ACCOUNT_HEALTH_COUNT_INFO';

//海外SKU统计
export const SAVE_OVERSEA_SKU_REPORT_INFO = 'SAVE_OVERSEA_SKU_REPORT_INFO';
export const SAVE_OVERSEA_CORE_SKU_REPORT_INFO = 'SAVE_OVERSEA_CORE_SKU_REPORT_INFO';

//各成本区间SPU开发数
export const SAVE_COST_SKU_DEV_GROUP_INFO = 'SAVE_COST_SKU_DEV_GROUP_INFO';
export const SAVE_COST_SKU_DEVELOPER_INFO = 'SAVE_COST_SKU_DEVELOPER_INFO';
export const SAVE_COST_SKU_DEV_TYPE_INFO = 'SAVE_COST_SKU_DEV_TYPE_INFO';
export const SAVE_COST_SKU_DEV_LINE_INFO = 'SAVE_COST_SKU_DEV_LINE_INFO';

//B2C订单执行率
export const SAVE_ORDER_RARE_DAY_INFO = 'SAVE_ORDER_RARE_DAY_INFO';
export const SAVE_ORDER_RARE_WEEK_INFO = 'SAVE_ORDER_RARE_WEEK_INFO';
export const SAVE_ORDER_RARE_MONTH_INFO = 'SAVE_ORDER_RARE_MONTH_INFO';

//采购组别配置
export const SAVE_PURCHASE_USER_CONFIG_INFO = 'SAVE_PURCHASE_USER_CONFIG_INFO';
export const SAVE_PURCHASE_GROUP_CONFIG_INFO = 'SAVE_PURCHASE_GROUP_CONFIG_INFO';

//国内仓核心SKU
export const SAVE_DOMESTIC_SKU_REPORT_INFO = 'SAVE_DOMESTIC_SKU_REPORT_INFO';
export const SAVE_DOMESTIC_CORE_SKU_REPORT_INFO = 'SAVE_DOMESTIC_CORE_SKU_REPORT_INFO';

//精品工作报表
export const SAVE_BOUTIQUE_SUMMARY_INFO = 'SAVE_BOUTIQUE_SUMMARY_INFO';
export const SAVE_BOUTIQUE_DETAILS_INFO = 'SAVE_BOUTIQUE_DETAILS_INFO';

//海外仓核心SKU周统计
export const SAVE_OVERSEA_SKU_WEEK_INFO = 'SAVE_OVERSEA_SKU_WEEK_INFO';
export const SAVE_OVERSEA_CORE_SKU_WEEK_INFO = 'SAVE_OVERSEA_CORE_SKU_WEEK_INFO';

//国内核心SKU周统计
export const SAVE_DOMESTIC_SKU_WEEK_INFO = 'SAVE_DOMESTIC_SKU_WEEK_INFO';
export const SAVE_DOMESTIC_CORE_SKU_WEEK_INFO = 'SAVE_DOMESTIC_CORE_SKU_WEEK_INFO';

//审核数量统计
export const SAVE_INFRINGE_GROUP_SUMMARY_INFO = 'SAVE_INFRINGE_GROUP_SUMMARY_INFO';
export const SAVE_INFRINGE_GROUP_DETAILS_INFO = 'SAVE_INFRINGE_GROUP_DETAILS_INFO';

//驳回次数统计
export const SAVE_REJECT_SUMMARY_INFO = 'SAVE_REJECT_SUMMARY_INFO';
export const SAVE_REJECT_DETAILS_INFO = 'SAVE_REJECT_DETAILS_INFO';
export const SAVE_REJECT_LINE_DETAILS_INFO = 'SAVE_REJECT_LINE_DETAILS_INFO';

//二次以上驳回统计
export const SAVE_MORE_REJECT_SUMMARY_INFO = 'SAVE_MORE_REJECT_SUMMARY_INFO';
export const SAVE_MORE_REJECT_DETAILS_INFO = 'SAVE_MORE_REJECT_DETAILS_INFO';

//阿米巴报表
export const SAVE_AMOEBA_SUMMARY_INFO = 'SAVE_AMOEBA_SUMMARY_INFO';
export const SAVE_AMOEBA_DETAIL_INFO = 'SAVE_AMOEBA_DETAIL_INFO';
export const SAVE_AMOEBA_CONFIG_INFO = 'SAVE_AMOEBA_CONFIG_INFO';

//亚马逊退单统计
export const SAVE_RETURN_ORDER_ACCOUNT_INFO = 'SAVE_RETURN_ORDER_ACCOUNT_INFO';
export const SAVE_RETURN_ORDER_SITE_INFO = 'SAVE_RETURN_ORDER_SITE_INFO';

//it费用清单
export const SAVE_SERVER_COST_INFO = 'SAVE_SERVER_COST_INFO';
export const SAVE_OTHER_COST_INFO = 'SAVE_OTHER_COST_INFO';

